output_dir:
prepare:
    features: 
        - sepal_length
        - sepal_width
        - petal_length
        - petal_width
    standardize: False
train:
    clf_params:
        criterion: gini
        max_depth: 2
validate:
    macro_avg_f1_score_min: 0.95
