output_dir:
prepare:
    features: 
        - sepal_length
        - sepal_width
    standardize: True
train:
    clf_params:
        criterion: gini
        max_depth: 10
validate:
    macro_avg_f1_score_min: 0.95
